version: '3'

volumes:
    command: cp -r /app/buil
  pg_data:
  static:

services:
  db:
    image: postgres:13
    restart: always
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    restart: always
    env_file: .env
    volumes:
      - static:/backend_static

  frontend:
    env_file: .env
    build: ./frontend/
    restart: always
    volumes:
      - static:/frontend_static

  gateway:
    build: ./gateway/
    restart: always
    env_file: .env
    volumes:
      - static:/staticfiles
    ports:
      - "8000:80"