server {
    listen 80;

    location /api/ {
        proxy_set_header Host $http_host;
        proxy_pass http://backend:8000/api/;
    }

    location /admin/ {
        proxy_set_header Host $http_host;
        proxy_pass http://backend:8000/admin/;
    }

    # Статика Django (Админка)
    location /static/admin/ {
        alias /app/static/backend/admin/;
    }

    # Статика Django (DRF)
    location /static/rest_framework/ {
        alias /app/static/backend/rest_framework/;
    }

    # Статика React (JS, CSS, картинки фронтенда)
    # React кладет их в /app/static/frontend/static/
    location /static/ {
        alias /app/static/frontend/static/;
    }

    # Главная страница и роутинг React
    location / {
        root /app/static/frontend/;
        try_files $uri $uri/ /index.html;
    }
}